codecov:
  token: "2f41f4fd-b863-46a2-ab93-dca1ff1eaaa1"
  bot: "codecov-io"
  ci:
    - "travis.org"
  strict_yaml_branch: "yaml-config"
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2
    wait_for_ci: yes
github_checks:
  annotations: false
